CREATE TABLE fantasy_stdev_2015(  
  id INTEGER PRIMARY KEY,
  first_name VARCHAR(50),
  last_name VARCHAR(50),
  games_played FLOAT,
  min FLOAT,
  fgm FLOAT,
  fga FLOAT,
  fg_pct FLOAT,
  fg3m FLOAT,
  fg3a FLOAT,
  fg3_pct FLOAT,
  ftm FLOAT,
  fta FLOAT,
  ft_pct FLOAT,
  oreb FLOAT,
  dreb FLOAT,
  reb FLOAT,
  ast FLOAT,
  stl FLOAT,
  blk FLOAT,
  tov FLOAT,
  atr FLOAT,
  pts FLOAT
);